# Autogenerated file.
# Do not edit.
# Do not change location.

message("Setting PQP 1.3 for linux-64")

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)


set(PQP_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE INTERNAL "" FORCE)
set(PQP_LIBRARIES "${ROOT_DIR}/lib/linux-64/libPQP.a;" CACHE INTERNAL "" FORCE)

set(PQP_TARGET "PQP" CACHE INTERNAL "" FORCE)

set(PQP_PACKAGE_FOUND "TRUE" CACHE INTERNAL "" FORCE)

set(PQP_DEPENDS "" CACHE INTERNAL "" FORCE)
 
